### ISSUE TITLE
TypeError: 'builtin_function_or_method' object is not iterable

### ISSUE THREAD

**Issue by zgxiangyang** [Zhaoyi-Yan/Shift-Net_pytorch#1]
File "/home/yaxian/image-creation/Shift_Net/Shift-Net_pytorch/data/aligned_dataset.py", line 33, in __getitem__
    w, h = AB.size
TypeError: 'builtin_function_or_method' object is not iterable

**Comment by Zhaoyi-Yan** [comment]
Please put 'AB=self.transforms(AB)' of Line 30 to Line 41.  Images are resized with ratio kept using PIL.
Then 'AB=self.transforms(AB)' transforms the images to a tensor. And finally random crop is applied.

**Comment by Zhaoyi-Yan** [comment]
Could you try the latest version of master. If solved, please notice us.
