### ISSUE TITLE
Performance of square masks is much better

### ISSUE THREAD

**Issue by muxgt** [Zhaoyi-Yan/Shift-Net_pytorch#102]
Hi! Thanks a lot for your work! I downloaded 2 pretrained face models and noticed that results of the model with square masks are much better than that with random masks despite that random masks are smaller than squares. Below is the example. Why do you think this is? Also do you think that model can be trained with higher resolutions?
![Untitled-1](https://user-images.githubusercontent.com/54779582/70392382-b05dbc80-19f0-11ea-84da-3235140525b1.jpg)

**Comment by Zhaoyi-Yan** [comment]
Hi, muxgt
In fact, it is the `fixed mask` is much better than random masks. `center square mask inpainiting` are specific mask that the mask is just at the center position with the fixed size square mask.

I think this model can be directly trained with higher resolutions (if GPU memory is bigger enough). For better performance, maybe you can refer to some relevent papers.

**Comment by muxgt** [comment]
Thank you for the answer!
