### ISSUE TITLE
Warnings flood the screen

### ISSUE THREAD

**Issue by muxgt** [Zhaoyi-Yan/Shift-Net_pytorch#103]
Hi @Zhaoyi-Yan! I'm training your model in Google Colab. When starting it floods the screen with user warnings during all training. Like this:
![1](https://user-images.githubusercontent.com/54779582/71275195-661bfa00-2365-11ea-90c6-bdef086b1f86.jpg) It is overloading the memory. How can I remove it? Or at least shut it down.

**Comment by Zhaoyi-Yan** [comment]
It is because that you use pytorch>=1.2, while the guys made ByteTensor deprecated. However, when I make this change, then the required version of this repo will be >=1.2.

**Comment by Zhaoyi-Yan** [comment]
I have push a commit to solve this, please check!

**Comment by muxgt** [comment]
Thanks a lot for such a speed! New commit gave error at line 160 in (1 - self.mask_global) saying it doesn't support subtraction in bool so I changed this to ~self.mask_global in line 160 and 177 and now it's working. Thanks again!
