### ISSUE TITLE
Issue related to --dataroot='./datasets/celeba-256/test'

### ISSUE THREAD

**Issue by Sasharanko** [Zhaoyi-Yan/Shift-Net_pytorch#107]
Hello, could you explain why I have the following problem when I have tried to execute - 
**python test.py --which_epoch=30 --name='paris_random_mask_20_30' --offline_loading_mask=1 --testing_mask_folder='masks' --dataroot='./datasets/celeba-256/test' --norm='instance'**
AssertionError: ./datasets/Paris/train is not a valid directory.
Do I need to download the dataset to make the inference, if so where can I do it?

**Comment by Zhaoyi-Yan** [comment]
I forget where I downloaded it before. However, maybe this link helps you: https://github.com/mazzzystar/make-CelebA-HQ
