### ISSUE TITLE
Making Shift-Net better for irregular face inpainting

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [Zhaoyi-Yan/Shift-Net_pytorch#108]
About 2 years ago, we find a new novel training strategy that boosts the peformance of face inpainting a lot.  This strategy was originally taken as the second novelty of Shift-Net v2 as the journel version. However, for some reason, I do not write the paper until now.  Unfortuatelly, I do not think Shift-Net v2 will come out in the furture. So I will release the code. It surpasses normal Shift-Net in the irregular face inpainting a lot!

**Comment by tchaton** [comment]
Hey @Zhaoyi-Yan, Can you share examples ?

**Comment by Zhaoyi-Yan** [comment]
![image](https://user-images.githubusercontent.com/29570378/75757933-38443000-5d6e-11ea-974e-0ca993ad09ff.png)
![image](https://user-images.githubusercontent.com/29570378/75757964-472ae280-5d6e-11ea-8b70-50465688aa07.png)

![image](https://user-images.githubusercontent.com/29570378/75758208-aee12d80-5d6e-11ea-9d42-c9e4c1342c03.png)
![image](https://user-images.githubusercontent.com/29570378/75758162-94a74f80-5d6e-11ea-8bd0-7d0bf8325c21.png)

![image](https://user-images.githubusercontent.com/29570378/75758383-f9fb4080-5d6e-11ea-976b-c12619e19c58.png)
![image](https://user-images.githubusercontent.com/29570378/75758445-18613c00-5d6f-11ea-9221-82b4321cef5c.png)

**Comment by Zhaoyi-Yan** [comment]
Many methods suffers from color shifting in inpainting regions for irregular mask inpainting.  Such phenomenon is quite severe when it comes to faces.  Our new training strategy helps deal with color shifting.

**Comment by tchaton** [comment]
Oh wow ! What did you change ?

**Comment by txytju** [comment]
Looking forward to the strategy!

**Comment by Zhaoyi-Yan** [comment]
@tchaton @txytju 
![face_flip_png](https://user-images.githubusercontent.com/29570378/76621620-cbe5df80-656a-11ea-92ba-09010ef552ea.jpg)

This is a brief overview of the new learning strategy. Each time,  for a image I, we shift in the features not only for I_feat, instead we search over I_feat and I_flip_feat to search the nearest pixel-level feature.

I will upload the code tomorrow.

**Comment by muxgt** [comment]
Hi @Zhaoyi-Yan! Where can I take this type of random masks for training?

**Comment by tchaton** [comment]
@Zhaoyi-Yan, Why forwarding the same mask. Won't it be easier to create 2 random masks (A and B), look into the other image embedding for the ken search (A -> B, B -> A), get the index, and select the feature within the initial outside mask embedding space. And add a loss, so the selected features matches based on that index. What do you think ?
