### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shuyongkang** [Zhaoyi-Yan/Shift-Net_pytorch#109]
File "C:\Users\shukang\Desktop\Shift-Net_pytorch-master\models\shift_net\shiftnet_model.py", line 84, in initialize
    self.vgg16_extractor = util.VGG16FeatureExtractor().to(self.gpu_ids[0])
IndexError: list index out of range

hello， I only use cpu to run test .py with paramaters --which_epoch=30 --name=paris_random_mask_20_30 --offline_loading_mask=1 --testing_mask_folder=masks --dataroot=./datasets/celeba-256/test --norm=instance --gpu_ids=-1,However the above error occurred，I did not modify any code.

**Comment by Zhaoyi-Yan** [comment]
It doesn't support cpu device currently. I will pull a request to sovle it.

**Comment by Zhaoyi-Yan** [comment]
Hi, I have update the code, please try and give me feedback whether it works for you.

**Comment by shuyongkang** [comment]
I tried again，It had works for me. thank you.
