### ISSUE TITLE
About face random inpainting test

### ISSUE THREAD

**Issue by optimalSolution-Q** [Zhaoyi-Yan/Shift-Net_pytorch#114]
I use the command that python test.py --which_model_netG='face_unet_shift_triple' --model='face_shiftnet' --name='face_random_mask_20_30' --which_epoch=30 --dataroot=./datasets/celeba-256/Celeba/ --offline_loading_mask=1  --norm='instance', but the output is that
![20200427191037](https://user-images.githubusercontent.com/41374112/80365849-d2ca7680-88ba-11ea-9965-9c5bcbf99fa4.png)
what should I do？
Thanks!

**Comment by Zhaoyi-Yan** [comment]
Hi, use it `cosine, latter_windows, i_2, i_3, i_1= Nonparm.cosine_similarity(former.clone().squeeze(), latter.clone().squeeze(), 1, stride, flag_cur)`

**Comment by Zhaoyi-Yan** [comment]
Hi, I modified two lines in the script, it is because that face shift-net is conducted very long ago, later I change the util/NonparametricShift.py in github, however, I do not change face_shift_net/InnerFaceShiftTripleFunction.py local.
Please try again, thank you!
