### ISSUE TITLE
Error in "InnerFaceShiftTripleFunction"

### ISSUE THREAD

**Issue by silence1114** [Zhaoyi-Yan/Shift-Net_pytorch#115]
Hi, in Shift-Net_pytorch-master/models/face_shift_net/InnerFaceShiftTripleFunction.py , line 88, 
the code : "ori_tmp = Nonparm._paste(latter_windows, ctx.ind_lst[idx], i_2, i_3, i_1, i_4)" 
i_2 to i_4 are not defined before, which causes NameError.

**Comment by Zhaoyi-Yan** [comment]
Oooooh, I forget I used these variables, I have push a commit to fix it, please try again and tell me whether it works.

**Comment by silence1114** [comment]
Thank you for your quick reply！now the program can run without errors
