### ISSUE TITLE
Question regarding neighbor searching.

### ISSUE THREAD

**Issue by Sasharanko** [Zhaoyi-Yan/Shift-Net_pytorch#119]
Hi, sorry for this question here, it doesn't apply to the implementation, but please help to understand how x*(y) = arg max...  from [Shift-Net: Image Inpainting via Deep Feature Rearrangement](https://arxiv.org/pdf/1801.09392.pdf) works.

**Comment by Zhaoyi-Yan** [comment]
Hi, it is not quite easy to explain unless you debug here: https://github.com/Zhaoyi-Yan/Shift-Net_pytorch/blob/master/models/shift_net/InnerShiftTripleFunction.py#L36,
```python
        cosine, latter_windows, i_2, i_3, i_1 = bNonparm.cosine_similarity(former_all.clone(), latter_all.clone(), 1, stride, flag)

        _, indexes = torch.max(cosine, dim=2)

        mask_indexes = (flag==1).nonzero()[:, 1].view(ctx.bz, -1)

        non_mask_indexes = (flag==0).nonzero()[:, 1].view(ctx.bz, -1).gather(1, indexes)

        idx_b = torch.arange(ctx.bz).long().unsqueeze(1).expand(ctx.bz, mask_indexes.size(1))
        # set the elemnets of indexed by [mask_indexes, non_mask_indexes] to 1.
        # It is a batch version
        ctx.ind_lst[(idx_b, mask_indexes, non_mask_indexes)] = 1
```
 ` _, indexes = torch.max(cosine, dim=2)` is what you want to find and  `ctx.ind_lst` is the matrix `P`.

**Comment by tchaton** [comment]
Hey @Zhaoyi-Yan,

I hope you are doing well. I lost your contact. Would be great to connect.
I was wondering if you were interested in pursing inpainting but in different data format.

I am currently one the main contributor of TorchPoints3d: https://github.com/nicolas-chaulet/torch-points3d.

And I guess ShiftNet would be pretty interesting to perform in-painting / densification in 3d.

Best regards,
T.C

**Comment by Sasharanko** [comment]
@Zhaoyi-Yan, thank you for your answer, it is really not easy and as I understand you're calculating Cosine Similarity for a pixel from missing region and then shift the most suitable pixel from know region in that place.

**Comment by Zhaoyi-Yan** [comment]
@tchaton 
I am sorry that I have devoted myself to another area, so I am afraid I do not have time to performing inpainting in 3d.
