### ISSUE TITLE
Planned Extensions on Shift-Net

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [Zhaoyi-Yan/Shift-Net_pytorch#20]
- High priority:
- [x] Update the code for pytorch >= 0.4.
- [x] Soft assignment instead of hard assignment.
- [x] Combine the shifted feature with original feature in a more elegant way. Eg. Residual,  complicated residual.
- Medium priority:
- [x] Relativistic discriminator.
- [x] Inception Module ?
- [x] Partial Conv ?

What's your opinion on this ? @tchaton

**Comment by Zhaoyi-Yan** [comment]
#22 This PR adds a lot of new features, thanks to @tchaton !

**Comment by tchaton** [comment]
I agree with the roadmap so far. 

I have added densenet based discriminator, and the game seems more equilibrated, as the generator is not easily winning.

I will focus on finishing U-Net Inception model, to give more power to the generator. However, I think we should also inspire ourself with DeepLabV3. Check this medium link from segmentation methods. We want the generator to be able to pull global features to fill up the gap, with shift layer help as much as possible.
(https://medium.com/@arthur_ouaknine/review-of-deep-learning-algorithms-for-image-semantic-segmentation-509a600f7b57)
