### ISSUE TITLE
BUG: SoftShift is broken

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [Zhaoyi-Yan/Shift-Net_pytorch#25]
As the `Nonparametric` is modified, `_paste` is no long what it means before. Need a fix, when the  final `Nonparametric` is decided.

**Comment by tchaton** [comment]
I am going to work on that :)

**Comment by tchaton** [comment]
![image](https://user-images.githubusercontent.com/12861981/50819574-53f6a680-1322-11e9-9d45-918254054535.png)
![image](https://user-images.githubusercontent.com/12861981/50819584-607aff00-1322-11e9-8c45-e6dc9cc9e73e.png)

It seems correct for me. You make the linear combinaison, and then u assign it. But you are right the function name is not pasting anymore.

**Comment by Zhaoyi-Yan** [comment]
It is correct!
