### ISSUE TITLE
Guidance loss is not compatible for multi-gpu

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [Zhaoyi-Yan/Shift-Net_pytorch#37]
It is not easy to solve, in fact.

I have no idea on how to solve it.

I once write another kind of `InnerCos.py` which only works on multi-gpu but not suitable for single-gpu.

I do not know how to solve it by now.

**Comment by tchaton** [comment]
Hello Yan,

I am going to look into that.

Best,
T.C

**Comment by Zhaoyi-Yan** [comment]
@tchaton 
I got some results, share with you via your personal e-mail or another one?

**Comment by tchaton** [comment]
My email adress is thomas.chaton.ai@gmail.com. Please share on this one  :)

**Comment by Zhaoyi-Yan** [comment]
@tchaton Hope this one can be solved asap.

**Comment by Zhaoyi-Yan** [comment]
#72
