### ISSUE TITLE
I will refine the code in these aspects.

### ISSUE THREAD

**Issue by Naruto-Sasuke** [Zhaoyi-Yan/Shift-Net_pytorch#6]
- [x] Simplify the code of `networks.py`. It is redundant and a little bit complex for now.
- [x] Add `init_gain` option.
- [x] Make it multi-gpu compatibility. 
Two more aspects:
- [x] Printing information of `InnerCos` and `Shift` layer.
- [x] Add `Skip` to `InnerCos` as a workaround.

The main difficulty lies in the implementation`InnerCos`. The target of `InnerCos` is not on the same GPU as that of its input. Multi-gpu support counts for a great deal when handling enormous datasets.

**Comment by Naruto-Sasuke** [comment]
#5

**Comment by Zhaoyi-Yan** [comment]
It looks generally good. For the third item, FYI, you can add `skip` defining whether one can skip the `InnerCos` layer. It is a workaround.  Finally, we hope a better way to add `InnerCos` as well as multi-gpu supported.

**Comment by Naruto-Sasuke** [comment]
Two more aspects:
- [x] Printing information of `InnerCos` and `Shift` layer.
- [x] Add `Skip` to `InnerCos` as a workaround.

**Comment by Naruto-Sasuke** [comment]
It is quite interesting to make `InnerCos` support multi-gpu training. I will makes a PR soon.

**Comment by Zhaoyi-Yan** [comment]
Have finished multi-gpu training with `InnerCos` via a265c6b
