### ISSUE TITLE
training stop

### ISSUE THREAD

**Issue by Mengyao-Li** [Zhaoyi-Yan/Shift-Net_pytorch#78]
I have a 1080Ti GPU ,and when I'm training,the training stops at third epoch.And I have tried again,it stopped at third epoch too,have you met this question?Why?Thanks.

**Comment by Zhaoyi-Yan** [comment]
I haven't met this problem, Any error messages will help.  You may try codebase two commits before https://github.com/Zhaoyi-Yan/Shift-Net_pytorch/tree/b08953371b6f487f43fca10042f5d06f6bd6ec18  , I haven't train for a long time for the latest version.

**Comment by Mengyao-Li** [comment]
It just stop at epoch:3, iters:5500,time:  XXX ,data: XXX , and don't go on,print no messages.Have you trained the lastest version?

**Comment by Zhaoyi-Yan** [comment]
I trained the latest version, it should be something unstable with `BCEWithLogitsLoss`. The training is totally stopped with GPU usage equals to 0 after about 3 epochs. I will investigate it.

**Comment by Zhaoyi-Yan** [comment]
Please try code two commits before, and see whether it is solved.

**Comment by Mengyao-Li** [comment]
Ok,I will try it,thanks.

**Comment by Zhaoyi-Yan** [comment]
I have replace BCEWithLogits with BCEloss back and have verified its stableness for 4 epochs, it should be ok. https://github.com/Zhaoyi-Yan/Shift-Net_pytorch/commit/c765939bed64b9604e9ea7ce2c14b2b2c69046d4

**Comment by Mengyao-Li** [comment]
I have tried code c765939,but it stopped at 3 epoch again,and I have tried codebase two commits before,it stopped at 3 epoch too.Do you know the reason?

**Comment by Zhaoyi-Yan** [comment]
Quite weird. I have trained 5 epochs and haven't seen such problem. Do you train from the very beginning or perform continue_training ?

**Comment by Mengyao-Li** [comment]
My dataset is celebA,and I select 11000 training images,and I set the dataroot as the path of celebA, then I run python3 train.py  --batchSize=1  --use_spectral_norm_D=1 --which_model_netD='basic'  --mask_type='center' --which_model_netG='unet_shift_triple'  --model='shiftnet'  --shift_sz=1  --mask_thred=1,then it stoped at 3 epoch.My environment is ubuntu16.04,pytorch1.0,visdom,dominate,scikit-image,python3.5

**Comment by Zhaoyi-Yan** [comment]
How about change these options `--which_model_netG='res_patch_soft_unet_shift_triple' --model='res_patch_soft_shiftnet'  --shift_sz=3 --mask_thred=4 `. Let me know whether this network works fine.

**Comment by Mengyao-Li** [comment]
It stopped at 3 epoch again.

**Comment by Zhaoyi-Yan** [comment]
How about sharing your dataset with me by email, and I will try to run with it to confirm the situation.  Also, can you run the model on Paris dataset to see whether it attributes to the dataset?

**Comment by Mengyao-Li** [comment]
May I ask what your email is?

**Comment by Zhaoyi-Yan** [comment]
yanzhaoyiAtoutlook.com

**Comment by Mengyao-Li** [comment]
我训练时选择了前11000张图片，非常感谢你的帮助


------------------ 原始邮件 ------------------
发件人: "Zhaoyi-Yan"<notifications@github.com>;
发送时间: 2019年4月25日(星期四) 下午2:48
收件人: "Zhaoyi-Yan/Shift-Net_pytorch"<Shift-Net_pytorch@noreply.github.com>;
抄送: "木头人"<1592884408@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Zhaoyi-Yan/Shift-Net_pytorch] training stop (#78)




yanzhaoyiAtoutlook.com
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

img_align_celeba.zip (1.34G, 2019年05月25日 15:07 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2d383230d376979bdc44c36e1f65531d000e06545a5d51544909565109485500520d1f085c00501f5d0f03005a0459045d0f05033971615b095f6d51550c065c3b5b575c5c07001c1e51423004&t=exs_ftn_download&code=d8209ea2

**Comment by Zhaoyi-Yan** [comment]
Set `nThread=4` if you met such problem.
