### ISSUE TITLE
Seems I have found a way to solve peformance degradation when training with batchsize>1

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [Zhaoyi-Yan/Shift-Net_pytorch#86]
Usually, Such UNet suffers with small training batchsize when training with fixed mask(usually batchsize=1),  now, I find a easy way to solve it.

**Comment by tchaton** [comment]
@Zhaoyi-Yan. How do you think to solve it ? :)

**Comment by Zhaoyi-Yan** [comment]
6b088076e8bbd1c153b72d25a868a89bd20fa0d1  Replace with instance norm with switchable norm, also with more epochs of training. For example, instance norm 30 epochs for Paris dataset when batchsize=1, yet need 50 epochs when adopting switchable norm.
